#!/bin/bash
echo "╔══════════════════════════════════════════════════════╗"
echo "║     Galaxy S7 Homelab - HTTPS Verification          ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "🔐 SECURITY STATUS: HTTPS ACTIVE ✅"
echo ""
echo "📡 Listening Ports:"
echo "   Port 8080: HTTP (Redirects to HTTPS)"
echo "   Port 8443: HTTPS (Secure)"
echo "   Port 8022: SSH (Remote Management)"
echo ""
echo "🌐 Access Points:"
echo "   1. 🔒 SECURE DASHBOARD:"
echo "      https://192.168.100.225:8443/dashboard.php"
echo ""
echo "   2. 🔒 SECURITY STATUS:"
echo "      https://192.168.100.225:8443/security-status.php"
echo ""
echo "   3. 🌐 HTTP AUTO-REDIRECT:"
echo "      http://192.168.100.225:8080"
echo "      (Will automatically redirect to HTTPS)"
echo ""
echo "   4. 🔑 SSH REMOTE ACCESS:"
echo "      ssh u0_a194@192.168.100.225 -p 8022"
echo ""
echo "⚠️  IMPORTANT: Browser will show security warning"
echo "   This is NORMAL for self-signed certificates"
echo "   Click 'Advanced' → 'Proceed to site'"
echo ""
echo "🧪 Quick Tests:"
curl -s -k https://localhost:8443 > /dev/null && echo "   ✅ HTTPS: Working" || echo "   ❌ HTTPS: Failed"
curl -s -I http://localhost:8080 2>/dev/null | grep -q "301" && echo "   ✅ HTTP Redirect: Working" || echo "   ❌ HTTP Redirect: Failed"
ls ~/ssl/selfsigned.crt > /dev/null 2>&1 && echo "   ✅ SSL Certificate: Present" || echo "   ❌ SSL Certificate: Missing"
echo ""
echo "🎉 SETUP COMPLETE!"
echo "   Your Galaxy S7 Homelab is now secured with HTTPS."
echo "   All HTTP traffic automatically redirects to secure HTTPS."
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║               MISSION ACCOMPLISHED! 🚀              ║"
echo "╚══════════════════════════════════════════════════════╝"
